version: '3.9'

services:
  db:
    container_name: pg-db
    image: postgres:14.0-alpine
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"


